### ISSUE TITLE
readcovearge_bam.jlのコードについて

### ISSUE THREAD

**Issue by TsubaMukku** [bioinfo-tsukuba/ReadCoverage.jl#4]
1. line50の、binNumbersという変数ですが、bin_numbersに変更しませんか？？

2. line96のreadLeftPosという変数名ですが, read_left_posに変更しませんか？

3. line133のblockSizeをblock_sizesに、line134のLをｌ（小文字のL、しかし、1とlは間違えそうな印象です。ここはLでもいいのかなと私は正直思いますが）に、line135のblockStartsをblock_startsに変更しませんか？

4. line186ですが、(2)と同様の変更をしませんか？

**Comment by TsubaMukku** [comment]
https://github.com/bioinfo-tsukuba/ReadCoverage.jl/blob/master/src/readcovearge_bam.jl

**Comment by yuifu** [comment]
こんな感じ

----

https://github.com/bioinfo-tsukuba/ReadCoverage.jl/blob/master/src/readcovearge_bam.jl の

line50の〜

**Comment by TsubaMukku** [comment]
わかりました。気をつけます

**Comment by yuifu** [comment]
> 1. line50の、binNumbersという変数ですが、bin_numbersに変更しませんか？？

OK

**Comment by yuifu** [comment]
2. line96のreadLeftPosという変数名ですが, read_left_posに変更しませんか？

`read_leftpos` にしましょう

4. も同様

**Comment by yuifu** [comment]
> line133のblockSizeをblock_sizesに、line134のLをｌ（小文字のL、しかし、1とlは間違えそうな印象です。ここはLでもいいのかなと私は正直思いますが）に、line135のblockStartsをblock_startsに変更しませんか？

block_sizes → OK

block_starts → OK

L -> transcript_length
