### ISSUE TITLE
absolute_genebodycoverage.jlのコード（変数）について

### ISSUE THREAD

**Issue by TsubaMukku** [bioinfo-tsukuba/ReadCoverage.jl#5]
https://github.com/bioinfo-tsukuba/ReadCoverage.jl/blob/master/src/absolute_genebodycoverage.jl

について

line 58において、read coverageに対する配列の命名として, covは一般的（慣例としてある）だという理解で良いですか？？

**Comment by yuifu** [comment]
`coverage` の方がいい気がします

**Comment by TsubaMukku** [comment]
了解です

**Comment by TsubaMukku** [comment]
了解です

**Comment by TsubaMukku** [comment]
了解です
